/* Sage — Minor Arcana, part two: Swords and Pentacles. Appended to SAGE.CARDS. */
(function (S) {
  'use strict';

  var SW = 'swords', P = 'pentacles';

  S.CARDS = S.CARDS.concat([

  /* ========================= SWORDS — AIR ========================= */

  { id:'swords-01', name:'Ace of Swords', arcana:'minor', suit:SW, num:1, element:'Air', astro:'Root of Air',
    img:'Swords01.jpg',
    kwU:['breakthrough','clarity','truth','a decisive idea','cutting through'],
    kwR:['confusion','a truth misused','clouded thinking','clarity that wounds'],
    up:'A clean cut through confusion. The Ace of Swords is the moment the truth becomes speakable — an insight that reorganises everything, a decision that finally becomes obvious, the right word found. It is double-edged by design: this clarity will cost something, and it is worth it.',
    rev:'Reversed, the blade is dull or badly aimed. Muddled thinking, a truth deployed to wound rather than to clarify, or an insight you keep almost having. It can mark information that is technically accurate and entirely misleading.',
    sym:'A hand from a cloud grips an upright sword crowned with a laurel and an olive branch — victory and peace, both. Six yods fall. The mountains below are jagged and bare: the territory of pure intellect has no shelter.',
    advice:'Say the true thing plainly. Precision now saves months of ambiguity.' },

  { id:'swords-02', name:'Two of Swords', arcana:'minor', suit:SW, num:2, element:'Air', astro:'Moon in Libra',
    img:'Swords02.jpg',
    kwU:['stalemate','avoided decision','wilful blindness','uneasy truce','impasse'],
    kwR:['the blindfold off','information arriving','a decision forced','release'],
    up:'A decision held in perfect suspension, at cost. The Two of Swords is the impasse you are maintaining by refusing to look — two options balanced, and the balance preserved by not gathering the information that would tip it. It is a defensive posture and it is exhausting. Something has to come down.',
    rev:'Reversed, the blindfold comes off. New information arrives, the stalemate breaks, or events decide for you. It is usually a relief even when the outcome is not the one you wanted, because the holding was the harder part.',
    sym:'She sits blindfolded, arms crossed over her chest with two swords balanced perfectly. Behind her the sea is scattered with rocks — hazards she cannot see. A crescent moon: this is happening in the dark, and by feel.',
    advice:'Gather the one fact you have been avoiding. Then decide.' },

  { id:'swords-03', name:'Three of Swords', arcana:'minor', suit:SW, num:3, element:'Air', astro:'Saturn in Libra',
    img:'Swords03.jpg',
    kwU:['heartbreak','painful truth','betrayal','grief','necessary hurt'],
    kwR:['beginning to heal','the worst passing','releasing pain','a wound reopened'],
    up:'It hurts, and the hurt is accurate. The Three of Swords is heartbreak caused by truth — the thing said, the thing found out, the loss that words made real. The card offers no comfort about the pain, but it is clean: this is not confusion, it is grief, and grief resolves in a way confusion does not.',
    rev:'Reversed, the sharpest part is passing. Healing begins, the pain becomes bearable, or you finally stop reopening it deliberately. Less often it means a wound is being nursed past its natural life, or a hurt not yet allowed to be felt at all.',
    sym:'Three swords pierce a single red heart against grey rain. No figure, no landscape, nothing to soften it — the most abstract image in the deck. The rain will pass; the image includes weather, which changes.',
    advice:'Let it hurt on purpose for a defined time. Suppressed grief takes longer.' },

  { id:'swords-04', name:'Four of Swords', arcana:'minor', suit:SW, num:4, element:'Air', astro:'Jupiter in Libra',
    img:'Swords04.jpg',
    kwU:['rest','recovery','retreat','deliberate stillness','convalescence'],
    kwR:['restlessness','returning too soon','burnout','forced stop'],
    up:'Stop. The Four of Swords is mandated rest — not defeat, but the recovery that makes continuing possible. It follows the heartbreak of the Three and it is the correct response to it. This is a card of contemplation, retreat, sick leave, and the sleep you have been postponing. Nothing needs to be decided today.',
    rev:'Reversed, rest is refused or forced. Restlessness that will not permit stillness, going back to work before you have healed, or a stop imposed by collapse rather than chosen. It can also signal the end of a retreat — time to re-enter.',
    sym:'A knight lies in effigy on a tomb, hands in prayer. Three swords hang above him; one lies beneath — the fight is set down but not far away. A stained glass window shows a figure receiving a blessing. He is not dead; he is resting.',
    advice:'Book the actual rest. Put it in the calendar as a commitment, not a gap.' },

  { id:'swords-05', name:'Five of Swords', arcana:'minor', suit:SW, num:5, element:'Air', astro:'Venus in Aquarius',
    img:'Swords05.jpg',
    kwU:['hollow victory','winning at a cost','conflict','self-interest','defeat'],
    kwR:['making amends','walking away','releasing a grudge','open conflict'],
    up:'You can win this and it will cost more than it returns. The Five of Swords is the argument won by playing dirty, the point proved at the expense of a relationship, the victory that leaves you standing alone in a field. Sometimes the card marks you as the loser instead — either way, the counsel is the same: consider conceding.',
    rev:'Reversed, the conflict resolves or is escaped. Amends made, a grudge released, a fight walked away from before it is winnable. Less happily, it can mean the conflict is escalating into the open after a period of covert hostility.',
    sym:'A smirking figure gathers up the swords while two others walk away, heads down. The sky is ragged and torn. He has all the weapons and no company — the image is very clear about which is worth more.',
    advice:'Concede the point. Being right is currently the expensive option.' },

  { id:'swords-06', name:'Six of Swords', arcana:'minor', suit:SW, num:6, element:'Air', astro:'Mercury in Aquarius',
    img:'Swords06.jpg',
    kwU:['transition','moving to calmer water','a necessary journey','gradual recovery'],
    kwR:['unable to move on','a return to trouble','resistance to change','baggage'],
    up:'Leaving rough water for smoother, carrying what happened with you. The Six of Swords is transition — a move, a recovery, a departure from a difficult period toward something quieter. It is not joyful and it is not meant to be; it is the grey, sober relief of things beginning to get easier.',
    rev:'Reversed, the crossing stalls. You cannot leave, you go back, or you make the journey and bring so much of the old situation that nothing changes. It occasionally marks a departure that is not yet possible and should not be forced.',
    sym:'A ferryman poles a boat carrying a cloaked figure and a child; six swords stand upright in the hull — the trouble travels with them, but it is stowed, not wielded. The water ahead is glassy, the water behind choppy.',
    advice:'Move first, process later. The calmer water is where the thinking happens.' },

  { id:'swords-07', name:'Seven of Swords', arcana:'minor', suit:SW, num:7, element:'Air', astro:'Moon in Aquarius',
    img:'Swords07.jpg',
    kwU:['stealth','strategy','getting away with it','deception','acting alone'],
    kwR:['exposure','coming clean','a plan unravelling','confession'],
    up:'Something is being done quietly, and not entirely straight. The Seven of Swords covers strategy, discretion, and outright deception — it does not always accuse you; often you are the one being worked around. Where it is favourable, it counsels cleverness over confrontation and acting alone rather than by committee.',
    rev:'Reversed, the cover is blown. Deception exposed, a scheme unravelling, or the decision to come clean before it is discovered. It can also mean stopping a self-deception you have been running for a long time.',
    sym:'He tiptoes away from a camp carrying five swords by the blades — awkwardly, at risk of cutting himself. Two remain stuck in the ground behind him: the plan is already incomplete. He looks back over his shoulder, grinning.',
    advice:'Check what is being carried by the blade. Clever plans here tend to cut the planner.' },

  { id:'swords-08', name:'Eight of Swords', arcana:'minor', suit:SW, num:8, element:'Air', astro:'Jupiter in Gemini',
    img:'Swords08.jpg',
    kwU:['feeling trapped','self-imposed limits','powerlessness','a mental prison'],
    kwR:['freeing yourself','seeing the way out','new perspective','still stuck'],
    up:'Trapped, mostly by belief. The Eight of Swords describes a situation that feels entirely without options and is not — the constraints are real but far looser than they appear from inside. It is a card about the stories that keep us in place, and it is not dismissive: the fear is genuine even when the cage is not locked.',
    rev:'Reversed, the bindings loosen. You see the way out, someone points it out, or you simply try the door. It can also intensify the upright meaning — deeper into the trap — so it is worth checking against the rest of the spread.',
    sym:'She is bound and blindfolded among eight swords — but the swords do not form a complete circle, and the ground beneath her is soft mud, not stone. Her bindings are loose. A castle sits on the hill above, indifferent.',
    advice:'List what is actually preventing you, in one sentence each. Most will not survive the writing.' },

  { id:'swords-09', name:'Nine of Swords', arcana:'minor', suit:SW, num:9, element:'Air', astro:'Mars in Gemini',
    img:'Swords09.jpg',
    kwU:['anxiety','sleeplessness','dread','mental anguish','the 3am mind'],
    kwR:['relief','fears named','recovery from anxiety','isolation with it'],
    up:'The suffering here is mental and it is disproportionate. The Nine of Swords is the three-in-the-morning card — anxiety, insomnia, guilt, the rehearsal of catastrophes that mostly do not arrive. The pain is entirely real. The card\'s quiet point is that the horror is in the room with you and not in the world.',
    rev:'Reversed, dawn comes. Anxiety releases its grip, a fear is spoken aloud and shrinks, help is finally asked for. Occasionally it means the anguish is being carried entirely in private, which prolongs it. Either way, this card responds well to being told to someone.',
    sym:'She sits up in bed with her face in her hands; nine swords hang on the black wall behind her, not touching her. The quilt is embroidered with roses and zodiac signs — the ordinary world, still there. Carved on the bed: one figure defeating another.',
    advice:'Say the fear out loud to one person. It is much smaller outside your head.' },

  { id:'swords-10', name:'Ten of Swords', arcana:'minor', suit:SW, num:10, element:'Air', astro:'Sun in Gemini',
    img:'Swords10.jpg',
    kwU:['rock bottom','a definitive ending','overkill','the worst of it','collapse'],
    kwR:['recovery','surviving it','slow improvement','refusing to get up'],
    up:'The bottom, and therefore the turn. The Ten of Swords is a total and slightly theatrical defeat — the thing ends comprehensively, there is nothing left to salvage, and there is a strange relief in that. It is over. The card is nearly always melodramatic about it, which is a hint: the situation is finished, and you are not.',
    rev:'Reversed, you get up. Recovery begins, the worst is behind you, improvement is slow but genuine. Less commonly it means resisting a recovery that is available — staying on the ground because the ground has become familiar.',
    sym:'He lies face down with ten swords in his back — far more than necessary, which is the point. But the sky is black only at the top: a golden dawn breaks along the horizon. His right hand is held in a blessing.',
    advice:'Accept that it is over and start from zero. There is nothing left here to defend.' },

  { id:'swords-11', name:'Page of Swords', arcana:'minor', suit:SW, num:11, element:'Air', astro:'Earth of Air',
    img:'Swords11.jpg',
    kwU:['curiosity','sharp questions','vigilance','learning fast','a candid message'],
    kwR:['gossip','scattered thinking','defensiveness','speaking without knowing'],
    up:'Alert, curious, and asking the questions everyone else is too polite to ask. The Page of Swords is intellectual appetite without yet the judgement to temper it — excellent for learning, research, and noticing what does not add up. As a message, it brings information, often blunt.',
    rev:'Reversed, the sharpness goes sideways. Gossip, opinions delivered with more confidence than basis, defensiveness disguised as debate, or a mind so scattered across inputs that nothing is actually being learned.',
    sym:'He stands on a hilltop holding a sword aloft in both hands, looking back over his shoulder. The clouds are ragged and birds scatter — turbulent air. His stance is braced; he is ready and slightly on edge.',
    advice:'Ask the awkward question. Do the research before you form the opinion.' },

  { id:'swords-12', name:'Knight of Swords', arcana:'minor', suit:SW, num:12, element:'Air', astro:'Air of Air',
    img:'Swords12.jpg',
    kwU:['decisive action','directness','intellectual charge','fast pursuit','ambition'],
    kwR:['aggression','haste','bulldozing','argument for its own sake'],
    up:'Straight at it, at speed. The Knight of Swords is pure directed intellect and nerve — the person who says the thing, makes the call, and does not wait for consensus. Enormously effective in the short term. As advice, he says stop deliberating and move, and accept that some damage is the price of speed.',
    rev:'Reversed, speed becomes damage. Words that cannot be unsaid, a decision made too fast to be right, arguments pursued for the pleasure of arguing. He arrives, wins, and leaves someone else to handle the wreckage.',
    sym:'He charges full tilt, sword forward, cloak and plume streaming; the horse\'s eyes are wide. The trees bend hard and clouds race — the whole image is wind. He is the fastest thing in the deck and there is nothing ahead of him.',
    advice:'Move now, but write the message and reread it before sending.' },

  { id:'swords-13', name:'Queen of Swords', arcana:'minor', suit:SW, num:13, element:'Air', astro:'Water of Air',
    img:'Swords13.jpg',
    kwU:['clear judgement','honesty','independence','boundaries','experienced wisdom'],
    kwR:['coldness','bitterness','harsh words','cynicism from old wounds'],
    up:'She has been through it and she is not sentimental about it. The Queen of Swords is unclouded perception — she sees the situation exactly, says so kindly but without softening, and keeps excellent boundaries. Her wisdom is earned through loss. As advice: be honest, be specific, and stop protecting people from accurate information.',
    rev:'Reversed, clarity hardens into cynicism. Bitterness worn as realism, criticism that lands harder than intended, or a defence against further hurt that has become the whole personality. It can also indicate someone whose honesty is a weapon.',
    sym:'She sits in profile, sword upright, one hand extended — receiving or holding at bay. A butterfly on her crown, tassel at her wrist: transformation and grief both. One bird flies above; the clouds below her have cleared.',
    advice:'Say it accurately and kindly. Both, not one.' },

  { id:'swords-14', name:'King of Swords', arcana:'minor', suit:SW, num:14, element:'Air', astro:'Fire of Air',
    img:'Swords14.jpg',
    kwU:['authority through reason','ethics','impartial judgement','intellectual power'],
    kwR:['cold logic','abuse of authority','rigid thinking','judgement without mercy'],
    up:'Reason with the power to enforce itself. The King of Swords is the judge, the strategist, the person whose authority rests on being consistently right and consistently fair. He is unmoved by sentiment and that is his value. As advice: apply the principle regardless of who it inconveniences, including yourself.',
    rev:'Reversed, principle without humanity. Logic used to justify cruelty, rules applied to the letter and against the spirit, authority defended rather than exercised. It can also indicate advice from someone qualified but not disinterested.',
    sym:'He faces us squarely, sword held slightly tilted to his right, in the judging position. Butterflies and a crescent moon on his throne; two birds above; the trees behind are still. The clouds have settled — the storm of thought resolved into law.',
    advice:'Apply your own rule to yourself first. Then enforce it without apology.' },

  /* ======================= PENTACLES — EARTH ======================= */

  { id:'pentacles-01', name:'Ace of Pentacles', arcana:'minor', suit:P, num:1, element:'Earth', astro:'Root of Earth',
    img:'Pents01.jpg',
    kwU:['tangible opportunity','a new resource','prosperity beginning','a seed'],
    kwR:['missed opportunity','poor timing','a shaky foundation','delayed material gain'],
    up:'Something solid is offered. The Ace of Pentacles is the material beginning — a job, an income stream, a home, a resource, a genuinely practical opportunity. Unlike the other aces it comes with weight and can actually be held. It requires planting rather than admiring: this seed does nothing in your hand.',
    rev:'Reversed, the opportunity slips or was never as solid as it looked. Bad timing, a foundation that will not bear weight, or a material chance not taken and now gone. It can also mean prosperity delayed rather than denied.',
    sym:'A hand offers a single large pentacle above a walled garden in full bloom, with an arched gateway leading out to mountains. The gate is open. The pentacle floats — it has not been planted yet.',
    advice:'Plant it this week. Open the account, sign the thing, book the first hour.' },

  { id:'pentacles-02', name:'Two of Pentacles', arcana:'minor', suit:P, num:2, element:'Earth', astro:'Jupiter in Capricorn',
    img:'Pents02.jpg',
    kwU:['juggling','adaptability','balance in motion','managing demands','flexibility'],
    kwR:['dropping the ball','overcommitment','disorganisation','losing the rhythm'],
    up:'Two demands, one pair of hands, and you are actually managing it. The Two of Pentacles is dynamic balance — the money, the schedule, the two jobs, the competing priorities — held in motion rather than resolved. It is sustainable for a while and it requires staying light on your feet.',
    rev:'Reversed, the juggling fails. Too many commitments, a dropped priority, finances or time that no longer balance. It usually means one thing must actually be set down rather than shuffled faster.',
    sym:'He dances while juggling two pentacles inside a green lemniscate — infinite, continuous motion. Behind him, two ships ride enormous waves without capsizing: the conditions are rough and he is managing anyway.',
    advice:'Keep two plates spinning at most. A third is where this card breaks.' },

  { id:'pentacles-03', name:'Three of Pentacles', arcana:'minor', suit:P, num:3, element:'Earth', astro:'Mars in Capricorn',
    img:'Pents03.jpg',
    kwU:['craftsmanship','collaboration','skill recognised','building well','apprenticeship'],
    kwR:['poor teamwork','work undervalued','mediocre effort','ignoring expertise'],
    up:'Skilled work, done with others, on something that will last. The Three of Pentacles is the card of craft — competence recognised, a team where each person contributes their actual expertise, the early stages of building something properly. It rewards doing the job well over doing it fast.',
    rev:'Reversed, the collaboration is off. Expertise ignored, credit misallocated, work rushed to a standard nobody is proud of, or a team where roles are unclear. It can also mean you are underselling skill you have genuinely earned.',
    sym:'A sculptor stands on a bench in a cathedral while a monk and a nobleman consult plans with him — labour, faith, and money at the same table, all three necessary. The three pentacles are carved into the arch: already part of the structure.',
    advice:'Bring in the person who actually knows. Then do it to a standard you would sign.' },

  { id:'pentacles-04', name:'Four of Pentacles', arcana:'minor', suit:P, num:4, element:'Earth', astro:'Sun in Capricorn',
    img:'Pents04.jpg',
    kwU:['holding on','security','saving','control','conservation'],
    kwR:['letting go','generosity','loosening the grip','financial release'],
    up:'You are holding tightly, and it is working, and it is also costing you. The Four of Pentacles is security through retention — savings, caution, keeping what you have. There is nothing wrong with this and the card does not scold. It only notes that hands full of pentacles cannot pick anything else up.',
    rev:'Reversed, the grip loosens. Spending, giving, investing, or releasing something you have been clutching past its usefulness. Occasionally it warns of the opposite — an inability to hold onto anything, money or otherwise, moving out as fast as it comes in.',
    sym:'He sits on a stool outside the city, crown pentacle on his head, one clutched to his chest, two under his feet. Every pentacle is a point of contact and none of his limbs are free. The city behind him is where the life is.',
    advice:'Release one thing you are holding. Notice that nothing collapses.' },

  { id:'pentacles-05', name:'Five of Pentacles', arcana:'minor', suit:P, num:5, element:'Earth', astro:'Mercury in Taurus',
    img:'Pents05.jpg',
    kwU:['hardship','exclusion','material lack','feeling left out in the cold','isolation'],
    kwR:['recovery','help accepted','coming inside','the end of a hard stretch'],
    up:'Genuine hardship, made worse by isolation. The Five of Pentacles is material difficulty — money, health, work — combined with the feeling of being outside while others are warm. Its sharpest point is that help is usually nearer than it feels, and pride or shame is what keeps the door unopened.',
    rev:'Reversed, you come in from the cold. Help is asked for and given, the hard stretch ends, health or finances begin to recover. It is one of the deck\'s more reliable turns for the better, and it typically begins with admitting the need.',
    sym:'Two figures pass through snow beneath a lit stained-glass window — one on crutches, one barefoot. The window is bright, ornate, and directly above them. Neither looks up. The church is right there.',
    advice:'Ask for the help. The door you are walking past is not locked.' },

  { id:'pentacles-06', name:'Six of Pentacles', arcana:'minor', suit:P, num:6, element:'Earth', astro:'Moon in Taurus',
    img:'Pents06.jpg',
    kwU:['generosity','fair exchange','giving and receiving','support','balance restored'],
    kwR:['strings attached','uneven giving','debt','charity as power'],
    up:'Resources move to where they are needed. The Six of Pentacles is generosity and fair exchange — giving when you have, receiving when you do not, and the understanding that both roles come around. It often marks help arriving, or an opportunity to be the one who helps.',
    rev:'Reversed, the exchange has a hook in it. Gifts with conditions, generosity used to establish superiority, debts that never quite clear, or a pattern where you are always the giver or always the taker. Charity is doing work other than kindness here.',
    sym:'A merchant weighs scales in one hand while dropping coins to two kneeling beggars with the other. He has both the money and the scales — he decides both the amount and the fairness. That asymmetry is deliberate.',
    advice:'Give or ask, plainly and without conditions. Note who currently holds the scales.' },

  { id:'pentacles-07', name:'Seven of Pentacles', arcana:'minor', suit:P, num:7, element:'Earth', astro:'Saturn in Taurus',
    img:'Pents07.jpg',
    kwU:['patience','assessment','waiting for growth','long-term investment','review'],
    kwR:['impatience','poor return','wasted effort','pulling up the crop'],
    up:'You have done the work and now you have to wait. The Seven of Pentacles is the mid-season pause — the investment made, the crop not yet ripe, the moment for honest assessment of whether this is growing. It counsels patience, and it also permits the question of whether this field is worth another season.',
    rev:'Reversed, the patience runs out or the return does not come. Effort that has not paid off, a project abandoned just before harvest, or the realisation that you have been tending something that will not bear. Both diagnoses require the same honest look.',
    sym:'He leans on his hoe, gazing at a heavy vine bearing seven pentacles. His posture is weary and evaluative rather than pleased. One pentacle sits apart on the ground — something already harvested, or something fallen.',
    advice:'Give it one more defined season, then evaluate honestly against real numbers.' },

  { id:'pentacles-08', name:'Eight of Pentacles', arcana:'minor', suit:P, num:8, element:'Earth', astro:'Sun in Virgo',
    img:'Pents08.jpg',
    kwU:['diligence','skill-building','repetition','apprenticeship','focused work'],
    kwR:['perfectionism','uninspired repetition','cutting corners','skill unused'],
    up:'Reps. The Eight of Pentacles is the unglamorous accumulation of skill through repetition — practising, drafting, doing the same thing until it is good. It is one of the most reliably positive cards in the deck because its promise is entirely within your control: do the work and you will get better.',
    rev:'Reversed, the work goes wrong at either extreme. Perfectionism that will not let anything ship, or corners cut and quality slipping. It can also mean labour that has become mechanical — competence maintained with no learning left in it.',
    sym:'He hammers pentacles at a bench, one at a time; six are already mounted on the post beside him, one in progress, one at his feet. The town is in the distance — he has left the social world to do this. His whole attention is on the piece in his hands.',
    advice:'Do the reps. Set a number and hit it before you judge the results.' },

  { id:'pentacles-09', name:'Nine of Pentacles', arcana:'minor', suit:P, num:9, element:'Earth', astro:'Venus in Virgo',
    img:'Pents09.jpg',
    kwU:['self-sufficiency','earned comfort','independence','refinement','enjoying it'],
    kwR:['over-reliance','hollow luxury','independence as isolation','unearned comfort'],
    up:'You built this and you are allowed to enjoy it. The Nine of Pentacles is earned independence — financial self-sufficiency, a life arranged to your own taste, the pleasure of not needing anyone\'s permission. It is a card of quiet luxury and of discipline that has paid off. Take the afternoon.',
    rev:'Reversed, the independence is compromised or unsatisfying. Reliance on someone else\'s resources, comfort that came without the work and therefore does not feel like yours, or self-sufficiency maintained so strictly it has become loneliness.',
    sym:'She stands in a walled vineyard, hooded falcon on her gloved hand — a wild thing trained, a disciplined appetite. Nine pentacles among the vines, a manor behind. She is entirely alone, and entirely at ease.',
    advice:'Enjoy what you have built, deliberately and today. That is the assignment.' },

  { id:'pentacles-10', name:'Ten of Pentacles', arcana:'minor', suit:P, num:10, element:'Earth', astro:'Mercury in Virgo',
    img:'Pents10.jpg',
    kwU:['lasting wealth','legacy','family security','the long view','establishment'],
    kwR:['family friction over resources','short-termism','an unstable legacy'],
    up:'Wealth that outlasts you. The Ten of Pentacles is the long view — family security, inheritance, a business that endures, a foundation laid for people who come after. It is the most established card in the deck: not exciting, deeply solid. Decisions here should be made on a decade horizon.',
    rev:'Reversed, the structure has cracks. Money conflict inside a family, a legacy that is more burden than gift, short-term choices undermining long-term stability, or the question of whether you want the inheritance at all.',
    sym:'An old man in a patterned cloak sits with two dogs while a couple and a child stand under an archway; ten pentacles are arranged in the Tree of Life pattern. Three generations, and the elder is at the edge of the frame, unnoticed.',
    advice:'Make the decision that serves ten years from now, not this quarter.' },

  { id:'pentacles-11', name:'Page of Pentacles', arcana:'minor', suit:P, num:11, element:'Earth', astro:'Earth of Earth',
    img:'Pents11.jpg',
    kwU:['studiousness','a practical start','new skill','ambition','a tangible offer'],
    kwR:['procrastination','unrealistic plans','study avoided','an offer not pursued'],
    up:'A studious, practical beginning. The Page of Pentacles is enrolment — starting the course, taking the entry-level job, learning the thing properly from the ground. He is patient and unhurried and he means it. As a message, he brings a concrete offer worth taking seriously.',
    rev:'Reversed, the practical start stalls. Procrastination, plans that ignore the actual numbers, education abandoned, or an offer left unanswered until it expires. The ambition is real; the groundwork is missing.',
    sym:'He stands in a ploughed green field holding a pentacle up in both hands, studying it with total absorption. He is not moving. Trees and mountains distant — the whole landscape is cultivated, worked land.',
    advice:'Enrol. Sign up for the actual thing rather than reading about it.' },

  { id:'pentacles-12', name:'Knight of Pentacles', arcana:'minor', suit:P, num:12, element:'Earth', astro:'Air of Earth',
    img:'Pents12.jpg',
    kwU:['persistence','reliability','methodical progress','doing it properly','routine'],
    kwR:['stagnation','stubbornness','tedium','progress too slow to matter'],
    up:'Slow, thorough, and he will actually finish. The Knight of Pentacles is the least glamorous and most dependable figure in the deck — routine maintained, commitments kept, progress made at a rate that looks like nothing and adds up to everything. Where he appears, boring consistency is the winning strategy.',
    rev:'Reversed, thoroughness becomes inertia. Work that has stopped moving, stubbornness about a method that no longer fits, or a routine so entrenched it has become the point. The card asks whether this is patience or simply stuckness.',
    sym:'His horse is a heavy black plough-horse, standing completely still — the only stationary knight. Ploughed fields behind. He holds the pentacle up and looks at it steadily. Oak leaves on his helm and the horse\'s brow.',
    advice:'Same time, same thing, every day. Do not renegotiate it with yourself.' },

  { id:'pentacles-13', name:'Queen of Pentacles', arcana:'minor', suit:P, num:13, element:'Earth', astro:'Water of Earth',
    img:'Pents13.jpg',
    kwU:['practical nurture','resourcefulness','groundedness','providing well','warmth'],
    kwR:['self-neglect','smothering','financial worry','over-work'],
    up:'Care expressed as competence. The Queen of Pentacles nurtures by providing — the meal, the stable home, the practical help that actually solves the problem. She is warm, resourceful, and extremely good at the material world. As advice: attend to the physical basics, yours and other people\'s, and trust that this is not a small thing.',
    rev:'Reversed, she gives everything and keeps nothing. Self-neglect while everyone else is fed, financial anxiety running underneath the competence, or care that has become control. Her failure mode is always the same: she is not on her own list.',
    sym:'She sits in a bower of roses in a lush landscape, cradling her pentacle and gazing down at it like a child. A rabbit — fertility, abundance — hops in the lower corner. Everything around her is fruitful and everything is tended.',
    advice:'Put yourself on the list. Eat, sleep, and handle one practical thing for you.' },

  { id:'pentacles-14', name:'King of Pentacles', arcana:'minor', suit:P, num:14, element:'Earth', astro:'Fire of Earth',
    img:'Pents14.jpg',
    kwU:['material mastery','wealth','reliable provision','business sense','stability'],
    kwR:['greed','status anxiety','stubbornness','wealth without meaning'],
    up:'He has built it and it holds. The King of Pentacles is material mastery — the successful business, the sound investment, the person whose word on practical matters is worth taking. He is generous because he is secure, and unhurried because he does not need anything urgently. As advice: think like an owner, on a long horizon.',
    rev:'Reversed, wealth becomes the whole identity. Greed, status anxiety, decisions made purely for money, or a stubbornness about how things are done that has calcified. It can indicate someone materially successful and not much else.',
    sym:'His robe is embroidered with grape vines; his throne carved with bulls for Taurus. A castle behind, vines heavy around him, one foot on an armoured boot resting on a boar\'s head — old conquests, now decorative. He barely holds the pentacle; it simply sits with him.',
    advice:'Make the sound, unexciting financial decision. Then stop thinking about it.' },

  ]);
})(window.SAGE = window.SAGE || {});
