/* Sage — Minor Arcana. Appended to SAGE.CARDS.
 * Wands / Fire — drive, creativity, will, enterprise
 * Cups / Water — feeling, relationship, intuition, the inner life
 * Swords / Air — thought, truth, conflict, communication
 * Pentacles / Earth — body, money, work, the material world
 */
(function (S) {
  'use strict';

  var W = 'wands', C = 'cups', SW = 'swords', P = 'pentacles';

  S.CARDS = S.CARDS.concat([

  /* ========================= WANDS — FIRE ========================= */

  { id:'wands-01', name:'Ace of Wands', arcana:'minor', suit:W, num:1, element:'Fire', astro:'Root of Fire',
    img:'Wands01.jpg',
    kwU:['spark','inspiration','new venture','raw potential','desire'],
    kwR:['false start','delayed launch','flat energy','an idea without follow-through'],
    up:'A spark, offered. The Ace of Wands is the first surge of wanting-to — an idea that makes you sit up, an invitation, a creative impulse with genuine heat behind it. It is potential rather than achievement, and it is perishable: this energy is at its highest right now and will not stay at this pitch. Take it while it burns.',
    rev:'The spark did not catch. Reversed, this is enthusiasm that fizzled, a project announced and never begun, or a delay that has taken the heat out of something. It can also mean the impulse is there but you are sitting on it, waiting for a better moment that keeps not arriving.',
    sym:'A hand emerges from a cloud holding a living branch, leaves still sprouting from it. Below, a castle on a hill — the potential destination, not yet approached. Eight loose leaves fall, the yods of divine spark.',
    advice:'Act on it within forty-eight hours or admit you will not.' },

  { id:'wands-02', name:'Two of Wands', arcana:'minor', suit:W, num:2, element:'Fire', astro:'Mars in Aries',
    img:'Wands02.jpg',
    kwU:['planning','scope','future vision','a decision to expand','standing at the threshold'],
    kwR:['fear of the unknown','staying safe','poor planning','overthinking the map'],
    up:'The initial spark has become a plan with a horizon. The Two of Wands is the moment of surveying — you have something real in hand and are deciding how far to take it. There is a choice implied between the safe domain you already command and a larger, riskier field. The card generally favours looking outward.',
    rev:'Reversed, the world stays small. This is a plan endlessly refined rather than launched, an expansion talked about for years, or genuine fear of leaving somewhere you are already competent. Occasionally it is the opposite: a leap taken with no plan behind it at all.',
    sym:'He stands on the battlements holding a globe — the whole world in his hand, but he is still inside the castle. One wand is fixed to the wall, one he holds: what is settled and what is portable.',
    advice:'Set the horizon date. A plan without a departure time is a daydream.' },

  { id:'wands-03', name:'Three of Wands', arcana:'minor', suit:W, num:3, element:'Fire', astro:'Sun in Aries',
    img:'Wands03.jpg',
    kwU:['expansion underway','foresight','ships coming in','waiting well','enterprise'],
    kwR:['delays','plans returning empty','short-sightedness','impatience'],
    up:'The venture has launched and is out of your hands for now. The Three of Wands is the productive wait — the ships are at sea, the applications are in, the work is circulating. It carries confidence rather than anxiety, and it favours thinking bigger than you have been: the scope of what is possible is expanding.',
    rev:'Reversed, the returns are late or disappointing. Plans that were sent out come back empty, timelines slip, or you find the vision was too narrow to be worth the voyage. It can also indicate impatience corroding a wait that is proceeding normally.',
    sym:'He stands with his back to us on a high cliff, watching ships on the water. He holds one of the three staves and the other two stand behind him — invested, not idle. The gold ground suggests the venture is already prospering.',
    advice:'Widen the ask. You are currently planning for less than is available.' },

  { id:'wands-04', name:'Four of Wands', arcana:'minor', suit:W, num:4, element:'Fire', astro:'Venus in Aries',
    img:'Wands04.jpg',
    kwU:['celebration','homecoming','stable joy','milestone','community'],
    kwR:['muted celebration','instability at home','a milestone unmarked','transition'],
    up:'A genuine good moment, shared. The Four of Wands is homecoming, marriage, housewarming, the completion worth throwing a party for — happiness that is stable enough to stand on. It marks the arrival of a foundation, and it insists that arrivals be celebrated rather than absorbed and immediately built upon.',
    rev:'The celebration is thin, private, or postponed. Reversed, this can be tension in the home, a milestone reached without the sense of having arrived, or belonging that has not quite formed. It is rarely disastrous — more a joy that has not been allowed to fully land.',
    sym:'Four staves form a canopy hung with flowers and fruit; two figures raise bouquets beneath it. Behind them, a castle and a crowd — this is a public happiness. The canopy has no walls: the structure is light, open, welcoming.',
    advice:'Mark it. Invite someone, make the meal, say the toast out loud.' },

  { id:'wands-05', name:'Five of Wands', arcana:'minor', suit:W, num:5, element:'Fire', astro:'Saturn in Leo',
    img:'Wands05.jpg',
    kwU:['competition','friction','clashing energies','scrappy contest','productive conflict'],
    kwR:['conflict avoided','internal tension','exhaustion from fighting','resolution'],
    up:'Everyone wants something and no one is coordinating. The Five of Wands is a scrum rather than a war — competition, crossed purposes, a lot of noise and effort producing less than it should. It is not malicious, and it can be genuinely energising, but it is inefficient. Somebody needs to establish the rules.',
    rev:'Reversed, the fight goes underground or ends. This can be conflict avoided at the cost of never resolving it, tension internalised as anxiety, or the welcome exhaustion at the end of a contest. It also marks the moment competitors realise they want different things after all.',
    sym:'Five young men brandish staves in a chaotic tangle, but nobody is hurt and nobody is winning — it reads as much like a rehearsal or a game as a battle. The ground is uneven, the sky pale and open.',
    advice:'Name the actual prize. Half of this friction is people fighting over different things.' },

  { id:'wands-06', name:'Six of Wands', arcana:'minor', suit:W, num:6, element:'Fire', astro:'Jupiter in Leo',
    img:'Wands06.jpg',
    kwU:['victory','recognition','public success','confidence','good news'],
    kwR:['unrecognised effort','hollow win','fall from favour','ego'],
    up:'You win, and people see it. The Six of Wands is recognition — the promotion, the acceptance, the moment your work is publicly acknowledged. It differs from private satisfaction: this card is about being seen, and it counsels accepting the acknowledgement gracefully rather than deflecting it. Good news is genuinely likely here.',
    rev:'Reversed, the recognition does not come, comes to the wrong person, or arrives and feels empty. It can also mark a success held too tightly — pride that has started to alienate the people who helped. Occasionally it flags private achievement that simply does not need an audience.',
    sym:'The rider wears a laurel wreath and carries a laurel-crowned staff; the horse is draped and calm. Crucially, he is surrounded by others on foot — the victory is carried by a crowd, and he is above them.',
    advice:'Accept the credit without qualifying it. "Thank you" is the whole sentence.' },

  { id:'wands-07', name:'Seven of Wands', arcana:'minor', suit:W, num:7, element:'Fire', astro:'Mars in Leo',
    img:'Wands07.jpg',
    kwU:['defending your ground','conviction','holding the line','standing firm'],
    kwR:['overwhelmed','giving up ground','defensiveness','exhaustion'],
    up:'You have something worth defending and you are being challenged for it. The Seven of Wands is the position after victory — holding what you won, against more opponents than you would like, from a place of advantage you must not waste. It asks for conviction and stamina, and it says you can hold if you choose to.',
    rev:'Reversed, the defence is failing or was never necessary. This can be genuine overwhelm — too many fronts, not enough energy — or defensiveness in the absence of an actual attack, which costs the same and achieves nothing. It sometimes counsels ceding the position on purpose.',
    sym:'He stands on high ground fighting off six wands rising from below; he cannot see his attackers. Note his mismatched boots: he armed himself in a hurry. The high ground is the whole advantage.',
    advice:'Decide if this is worth defending. If it is, stop apologising for defending it.' },

  { id:'wands-08', name:'Eight of Wands', arcana:'minor', suit:W, num:8, element:'Fire', astro:'Mercury in Sagittarius',
    img:'Wands08.jpg',
    kwU:['speed','messages','swift movement','things landing at once','momentum'],
    kwR:['delays','scattered communication','rushing','messages missed'],
    up:'Everything moves at once. The Eight of Wands is acceleration — news arriving, travel, a situation that was static suddenly resolving fast. It is the most kinetic card in the suit and it usually means the waiting is over. Keep up, because the window is short and the momentum will not hold indefinitely.',
    rev:'Reversed, the arrows are grounded. Delays, crossed wires, messages that do not arrive or arrive garbled, a plan that will not gain speed. It can also mean things are moving so fast that nothing is landing properly and the correct response is to slow down deliberately.',
    sym:'Eight staves fly through open sky over a green landscape and a river — no figures at all, the only such card in the suit. They are descending, about to land. Everything about the image is transit.',
    advice:'Clear the decks. Whatever is coming needs room, and it is coming soon.' },

  { id:'wands-09', name:'Nine of Wands', arcana:'minor', suit:W, num:9, element:'Fire', astro:'Moon in Sagittarius',
    img:'Wands09.jpg',
    kwU:['resilience','last stand','wariness','nearly there','battle-tested'],
    kwR:['burnout','paranoia','giving up before the end','defences too high'],
    up:'Wounded but still standing, and closer to the end than it feels. The Nine of Wands is the card of endurance past the point of enthusiasm — you have been through it, you are guarded now, and you have one more push in you. Its counsel is that the wariness is earned but should not become permanent.',
    rev:'Reversed, the defences have outlasted the threat. This is burnout, suspicion of people who have done nothing, or quitting in the final stretch because the tank is empty. It asks honestly whether you are being attacked or simply exhausted, because those need different remedies.',
    sym:'He is bandaged about the head and leans on a staff, watching. Eight wands stand behind him like a fence — everything he has defended has become a wall. He is not looking at the wands; he is looking off to the side, at something we cannot see.',
    advice:'One more round, then rest properly. Do not mistake vigilance for progress.' },

  { id:'wands-10', name:'Ten of Wands', arcana:'minor', suit:W, num:10, element:'Fire', astro:'Saturn in Sagittarius',
    img:'Wands10.jpg',
    kwU:['overburden','carrying too much','duty','the cost of success','near the door'],
    kwR:['putting it down','delegation','collapse','releasing what is not yours'],
    up:'You are carrying more than one person should. The Ten of Wands is the weight of everything you said yes to, and it is close enough to home to be tempting to just push through. The card does not admire this. It notes that the load is obscuring your view and that some of these wands belong to other people.',
    rev:'Reversed, the burden is set down — willingly through delegation and refusal, or involuntarily through collapse. It is generally a relief, and it often accompanies the discovery that most of what you were carrying was never required of you in the first place.',
    sym:'He is bent double under ten staves, face hidden by the bundle. The village is visible ahead — he is almost there — but he cannot see it from that angle. Nothing in the image compels him to carry all ten.',
    advice:'Put down two things this week. Choose them now, not when you collapse.' },

  { id:'wands-11', name:'Page of Wands', arcana:'minor', suit:W, num:11, element:'Fire', astro:'Earth of Fire',
    img:'Wands11.jpg',
    kwU:['enthusiasm','a new interest','free spirit','exploration','good news'],
    kwR:['flakiness','scattered interest','bad news','all spark, no craft'],
    up:'Untrained enthusiasm, and it is charming. The Page of Wands is a beginner\'s excitement — the new hobby, the discovery, the person who has just found the thing they will become obsessed with. It is not yet skilled and does not need to be. As a message, it brings news that opens something up.',
    rev:'Reversed, the enthusiasm does not stick. Interests picked up and dropped, promises made in the flush of excitement and quietly abandoned, or a young person in your life who is all over the place. It can also mean the passion is real but the discipline to hold it has not arrived.',
    sym:'He holds his staff and looks up at it, absorbed — he is examining, not using. Salamanders on his tunic, the fire spirit. The desert behind is empty: nothing built yet, everything possible.',
    advice:'Let yourself be a beginner at something. Skip the part where you have to be good at it.' },

  { id:'wands-12', name:'Knight of Wands', arcana:'minor', suit:W, num:12, element:'Fire', astro:'Air of Fire',
    img:'Wands12.jpg',
    kwU:['bold action','charisma','adventure','headlong pursuit','passion'],
    kwR:['recklessness','burnout','impulsiveness','all charge, no finish'],
    up:'Charge. The Knight of Wands is passionate, magnetic, and utterly committed to whatever he is doing right now. He gets things moving that nobody else could move, and he makes life more interesting. As a person, he is exciting and unreliable in roughly equal measure; as a course of action, he says go now and adjust in flight.',
    rev:'Reversed, the charge becomes a crash. Impulsive decisions, a project abandoned at seventy percent for a shinier one, a temper, or a person whose intensity does not survive contact with routine. The energy is not wrong — the sustainability is.',
    sym:'The horse rears mid-stride, unstoppable; his armour is decorated with salamanders and his plume streams. The desert and three pyramids behind him: heat, distance, and a journey with no shade.',
    advice:'Go — but pick something you will still care about on a Tuesday.' },

  { id:'wands-13', name:'Queen of Wands', arcana:'minor', suit:W, num:13, element:'Fire', astro:'Water of Fire',
    img:'Wands13.jpg',
    kwU:['warm confidence','magnetism','courage','vivacity','self-possession'],
    kwR:['insecurity beneath the shine','jealousy','burnout','demanding attention'],
    up:'Confident, warm, and entirely herself. The Queen of Wands has the rare combination of high energy and genuine attention to others — she draws people because she is not performing. She governs creative leadership and social heat, and as advice she says: be more visibly yourself, and stop shrinking the thing that makes you interesting.',
    rev:'Reversed, the confidence is a front. This is insecurity managed through charm, jealousy of someone else\'s shine, or vivacity maintained past the point of exhaustion. It can also describe someone whose warmth is conditional on being the centre of the room.',
    sym:'She sits facing us directly, sunflower in one hand, staff in the other, legs apart and grounded. A black cat sits at her feet, looking straight out — her familiar, her shadow, unbothered. Lions on her throne, for Leo.',
    advice:'Take up the space. Warmth and confidence are not in conflict here.' },

  { id:'wands-14', name:'King of Wands', arcana:'minor', suit:W, num:14, element:'Fire', astro:'Fire of Fire',
    img:'Wands14.jpg',
    kwU:['visionary leadership','entrepreneurship','decisiveness','bold direction'],
    kwR:['tyranny','impulsive command','arrogance','vision without follow-through'],
    up:'Vision plus the authority to enact it. The King of Wands is the founder, the director, the person who sees where this could go and can get others to go there. He is decisive, occasionally impatient, and effective. As advice: take command of the direction, set it clearly, and trust people to execute rather than doing it yourself.',
    rev:'Reversed, leadership curdles into ego. Decisions made to demonstrate authority, impatience with anyone slower, big visions announced and never resourced. It can also mean a leader who has lost the plot, or your own reluctance to step into a role you are ready for.',
    sym:'He sits half-turned, as though about to stand and leave — he is not a settled king. Salamanders and lions on his throne and cloak; a live salamander at his feet, biting its own tail, fire made whole.',
    advice:'Decide the direction and say it plainly. Ambiguity from the top is expensive.' },

  /* ========================= CUPS — WATER ========================= */

  { id:'cups-01', name:'Ace of Cups', arcana:'minor', suit:C, num:1, element:'Water', astro:'Root of Water',
    img:'Cups01.jpg',
    kwU:['new feeling','emotional opening','love offered','overflow','grace'],
    kwR:['guarded heart','blocked feeling','emotion withheld','an offer declined'],
    up:'The heart opens. The Ace of Cups is a new emotional beginning — love offered, a friendship starting, compassion arriving unearned, or an overflow of feeling that surprises you. It is a gift rather than an achievement, and the only task is to be open enough to receive it. Creative and spiritual openings live here too.',
    rev:'Reversed, the cup is turned down or the water is not flowing. This is emotion held back, an offer you cannot accept, or a heart that has closed for good reasons and is now closed by default. It can mark grief that has not been allowed to move.',
    sym:'A hand offers a cup overflowing with five streams — more than the vessel can hold. A dove descends with the host; the lotus-covered water below receives everything. The W on the cup, inverted, is the M of water.',
    advice:'Say yes to the offer. Receiving is the harder half of this card.' },

  { id:'cups-02', name:'Two of Cups', arcana:'minor', suit:C, num:2, element:'Water', astro:'Venus in Cancer',
    img:'Cups02.jpg',
    kwU:['mutual attraction','partnership','a genuine meeting','reciprocity','truce'],
    kwR:['imbalance','disconnection','a one-sided bond','a rift'],
    up:'Two people meet as equals. The Two of Cups is mutual — attraction, respect, or partnership where both parties are giving and both are receiving. It covers romance, but equally friendship, collaboration, and reconciliation. Its distinguishing feature is reciprocity: this is not a card of longing, it is a card of connection actually made.',
    rev:'Reversed, the exchange is uneven. One person is carrying the relationship, communication has broken down, or an attraction is not returned in the way it is being given. It can also mark the rift before repair, or the honest recognition that a bond has run its course.',
    sym:'They exchange cups face to face, on level ground. Above them, the caduceus of Hermes with the winged lion\'s head — healing, and the passion that is being transmuted. Two snakes twine: balanced opposing forces.',
    advice:'Check the ledger. If it is lopsided, say so before resentment does it for you.' },

  { id:'cups-03', name:'Three of Cups', arcana:'minor', suit:C, num:3, element:'Water', astro:'Mercury in Cancer',
    img:'Cups03.jpg',
    kwU:['friendship','celebration','community','shared joy','reunion'],
    kwR:['overindulgence','a third party','social drain','isolation from your people'],
    up:'Joy that requires other people. The Three of Cups is friendship, celebration, and the particular happiness of being among your own — a reunion, good news shared, a night that everyone remembers. It is also the card of creative collaboration. Where it appears, the medicine is company.',
    rev:'Reversed, the party has a problem. Overindulgence, gossip, a third party disrupting a pair, or social obligation that drains rather than fills. It can also point to isolation — losing touch with the people who would restore you, usually by slow attrition rather than any rupture.',
    sym:'Three women dance in a circle, cups raised to touch above them. The ground is heavy with harvest — pumpkin, vine, fruit. Their circle is closed and complete; the joy is not seeking an audience.',
    advice:'Make the plan with the people who fill you. Actually put it in the calendar.' },

  { id:'cups-04', name:'Four of Cups', arcana:'minor', suit:C, num:4, element:'Water', astro:'Moon in Cancer',
    img:'Cups04.jpg',
    kwU:['apathy','discontent','withdrawal','missing what is offered','reevaluation'],
    kwR:['re-engagement','accepting the offer','emerging from a slump','new interest'],
    up:'Something is on offer and you cannot feel it. The Four of Cups is the flatness that comes not from disaster but from having enough and wanting something else — boredom, mild depression, the sense that nothing quite registers. It is a legitimate state and it is also blinding you to something being extended right now.',
    rev:'Reversed, you look up. The apathy lifts, the offer is finally noticed, interest returns. It often accompanies the small shift that ends a slump — not a revelation, just re-engagement. It can occasionally warn of accepting something out of restlessness rather than desire.',
    sym:'He sits under a tree, arms folded, staring at three cups on the ground; a hand from a cloud offers a fourth, which he does not see. His arms and legs are both crossed — closed on every axis.',
    advice:'Look up from the three cups. Something is being offered that you have not registered.' },

  { id:'cups-05', name:'Five of Cups', arcana:'minor', suit:C, num:5, element:'Water', astro:'Mars in Scorpio',
    img:'Cups05.jpg',
    kwU:['grief','loss','regret','mourning what spilled','partial disappointment'],
    kwR:['acceptance','turning around','moving on','forgiveness'],
    up:'A real loss, and an incomplete accounting of it. The Five of Cups sits with grief and regret honestly — something is genuinely gone and mourning it is correct. But the card is precise about the arithmetic: three cups spilled, two still standing. What remains is not visible from where you are looking.',
    rev:'Reversed, you turn around. Acceptance arrives, the remaining cups are noticed, forgiveness — of yourself or another — becomes possible. This is one of the more hopeful reversals in the deck: the grief has done its work and is beginning to release.',
    sym:'A cloaked figure faces three fallen cups; behind him, unnoticed, two stand upright. A bridge crosses the river to a castle — the way home exists and is not far. His head is bowed; he has not turned.',
    advice:'Grieve it properly, then turn around and count what is still standing.' },

  { id:'cups-06', name:'Six of Cups', arcana:'minor', suit:C, num:6, element:'Water', astro:'Sun in Scorpio',
    img:'Cups06.jpg',
    kwU:['nostalgia','innocence','kindness','the past returning','simple pleasure'],
    kwR:['stuck in the past','idealised memory','moving forward','naivety'],
    up:'The past visits kindly. The Six of Cups is nostalgia, childhood, and uncomplicated generosity — someone from before reappearing, a memory that comforts, a kindness given with nothing expected back. It is gentle and slightly wistful, and it often signals a return to something you used to love before it became complicated.',
    rev:'Reversed, the past has too much grip. Memory idealised past accuracy, a relationship maintained on what it used to be, or a refusal to grow up. Alternatively — and more happily — it means the past finally releases you and the orientation turns forward.',
    sym:'An older child offers a younger one a cup filled with white flowers, in the courtyard of a manor. Five more flowered cups stand about. A figure walks away in the background — the adult world, leaving them to it.',
    advice:'Do the small kind thing for no reason. That is the whole instruction.' },

  { id:'cups-07', name:'Seven of Cups', arcana:'minor', suit:C, num:7, element:'Water', astro:'Venus in Scorpio',
    img:'Cups07.jpg',
    kwU:['too many options','fantasy','illusion','wishful thinking','choice paralysis'],
    kwR:['clarity','choosing one','disillusion','seeing through it'],
    up:'Too many possibilities, most of them imaginary. The Seven of Cups is the fog of options — fantasies, daydreams, and genuine opportunities all presented in the same haze so that none can be evaluated. The card is not against dreaming; it is against mistaking the dream for a plan. One of these cups is real.',
    rev:'Reversed, the fog clears. A choice is made, an illusion is seen through, or a fantasy loses its glamour in a useful way. It is a relief, though sometimes a deflating one — the thing you wanted turns out to be ordinary.',
    sym:'Seven cups float in a cloud, each holding something: a face, a shrouded glowing figure, a snake, a castle, jewels, a laurel wreath, a dragon. The dreamer is a black silhouette — he has no substance in this vision at all.',
    advice:'Eliminate five. Test the remaining two in the real world within a week.' },

  { id:'cups-08', name:'Eight of Cups', arcana:'minor', suit:C, num:8, element:'Water', astro:'Saturn in Pisces',
    img:'Cups08.jpg',
    kwU:['walking away','leaving what is not enough','a deeper search','disenchantment'],
    kwR:['staying too long','fear of leaving','drifting back','aimless wandering'],
    up:'You leave something that was not bad. That is what makes the Eight of Cups hard: nothing here is broken, it is simply not enough, and going requires you to disappoint people whose questions you cannot fully answer. The card supports the departure. What you are looking for is not in this stack of cups.',
    rev:'Reversed, the departure stalls. You stay past the point of usefulness, return to something you already left, or leave without knowing what you are looking for and keep leaving. It can also mean a decision to stay and repair — valid, if consciously chosen.',
    sym:'He walks away under an eclipsed moon, staff in hand, toward high ground. Eight cups stand behind him, neatly stacked — but with a gap in the top row where one is missing. He is leaving something almost complete.',
    advice:'Go, even without the full explanation. "Not enough" is a sufficient reason.' },

  { id:'cups-09', name:'Nine of Cups', arcana:'minor', suit:C, num:9, element:'Water', astro:'Jupiter in Pisces',
    img:'Cups09.jpg',
    kwU:['satisfaction','a wish granted','contentment','pleasure','having enough'],
    kwR:['smugness','a wish that disappoints','indulgence','wanting the wrong thing'],
    up:'Traditionally the wish card. The Nine of Cups is emotional satisfaction — comfort, pleasure, a want that gets met. It is a little self-satisfied and that is allowed. Where it appears, something you have hoped for is likely to arrive, and the card gently asks you to notice the wanting itself, since you will get it.',
    rev:'Reversed, satisfaction is elusive or hollow. The wish is granted and disappoints, contentment tips into complacency, or pleasure is being used to avoid something. It sometimes indicates a want inherited from someone else, which is why fulfilling it does not land.',
    sym:'He sits arms folded before a curved counter draped in blue, nine cups arrayed behind him like a display. He looks pleased and slightly proprietary. The cups are behind him — his satisfaction is not something he is holding.',
    advice:'Be specific about the wish. Vague wanting gets vaguely answered.' },

  { id:'cups-10', name:'Ten of Cups', arcana:'minor', suit:C, num:10, element:'Water', astro:'Mars in Pisces',
    img:'Cups10.jpg',
    kwU:['emotional fulfilment','family','harmony','lasting happiness','belonging'],
    kwR:['a picture that does not match','strained family','misaligned ideals','the perfect image'],
    up:'The full version of what the suit was reaching for. The Ten of Cups is lasting emotional fulfilment — family, home, belonging, a happiness that includes other people and holds over time. It is idealistic and the card knows it, but where it appears the ideal is genuinely within reach or already quietly present.',
    rev:'Reversed, the picture and the reality diverge. Family strain, a home that looks right and does not feel right, or an ideal of happiness inherited rather than chosen. It asks whether you are pursuing your version of the ten cups or someone else\'s.',
    sym:'A couple stand with arms raised as two children dance; a rainbow of ten cups arcs overhead. The house, the river, the trees are all distant and small — the family is the foreground and the property is not.',
    advice:'Define your own version of this picture, in detail, before chasing anyone else\'s.' },

  { id:'cups-11', name:'Page of Cups', arcana:'minor', suit:C, num:11, element:'Water', astro:'Earth of Water',
    img:'Cups11.jpg',
    kwU:['a tender message','creative intuition','emotional openness','surprise feeling'],
    kwR:['emotional immaturity','moodiness','a message unsent','creative doubt'],
    up:'A soft, surprising message from the inner world. The Page of Cups brings news that touches you, an unexpected creative impulse, or the willingness to be sincere without irony. Its quality is unguarded — a little awkward, entirely genuine. As advice, it says share the feeling before you have polished it.',
    rev:'Reversed, feeling gets clumsy. Moodiness, sulking, an emotional reaction out of proportion, or a creative idea abandoned because the first attempt was bad. It can point to a message you have written and not sent.',
    sym:'He stands by the sea holding a cup from which a fish improbably rises, looking back at him. His response is bemused, not alarmed. His tunic is covered in lotuses; the sea behind him is choppy and alive.',
    advice:'Send the sincere message. Do not workshop it into safety first.' },

  { id:'cups-12', name:'Knight of Cups', arcana:'minor', suit:C, num:12, element:'Water', astro:'Air of Water',
    img:'Cups12.jpg',
    kwU:['romantic offer','following the heart','charm','an invitation','idealism'],
    kwR:['moodiness','unrealistic romance','disappointment','an offer with no substance'],
    up:'An offer made from the heart, delivered with style. The Knight of Cups is the romantic — proposals, invitations, artistic pursuit, following feeling wherever it leads. He moves slowly and deliberately, unlike the other knights. Where he appears, an approach is being made and it is sincere.',
    rev:'Reversed, the romance is a performance or a projection. Grand gestures with nothing behind them, moods presented as depth, or an ideal of love that no actual person can satisfy. It can also mark disappointment when a beautiful offer turns out to be empty.',
    sym:'His horse walks — the only knight not charging. He holds the cup out level, offering rather than carrying. Winged helm and heels, for Hermes; a river and mountains ahead, a journey with water in it.',
    advice:'Make the offer, or accept it. Then check what is actually behind it.' },

  { id:'cups-13', name:'Queen of Cups', arcana:'minor', suit:C, num:13, element:'Water', astro:'Water of Water',
    img:'Cups13.jpg',
    kwU:['emotional depth','empathy','intuition','holding others','compassionate wisdom'],
    kwR:['overwhelm','absorbing others\' feelings','martyrdom','emotional withdrawal'],
    up:'She feels everything and is not destabilised by it. The Queen of Cups is the deepest emotional intelligence in the deck — the person others bring their grief to, who holds it without drowning. She trusts intuition as data. As advice: attend to feeling carefully, yours and other people\'s, and let it inform the decision.',
    rev:'Reversed, the boundary between her feelings and everyone else\'s dissolves. Emotional overwhelm, caretaking that has become identity, or the opposite — a withdrawal so complete that nothing gets in. Both are what happens when depth is not protected.',
    sym:'Her cup is the only closed, ornate one in the deck — a lidded reliquary with angel handles. She gazes into it, absorbed. She sits at the water\'s edge but on stone, feet dry: in it and not in it.',
    advice:'Feel it, then ask what is yours to carry and what is not.' },

  { id:'cups-14', name:'King of Cups', arcana:'minor', suit:C, num:14, element:'Water', astro:'Fire of Water',
    img:'Cups14.jpg',
    kwU:['emotional mastery','calm authority','diplomacy','wise counsel','steadiness'],
    kwR:['suppression','manipulation via feeling','volatility','coldness'],
    up:'Feeling under command, without being denied. The King of Cups holds strong emotion and stays level — the person who is unflappable in a crisis because they are processing, not suppressing. He is diplomatic, kind, and hard to rattle. As advice: respond rather than react, and be the steady one.',
    rev:'Reversed, mastery becomes either suppression or manipulation. Feelings pushed down until they surface sideways, moods used to control a room, or a coldness presented as maturity. It can indicate someone whose calm is a wall rather than a skill.',
    sym:'His throne floats on turbulent water while he remains perfectly dry and still. A ship rides the swell behind him and a fish leaps — the sea is real and active, he simply is not moved by it. He wears a fish amulet at his throat.',
    advice:'Wait until you are level, then act. Nothing here is improved by reacting now.' },

  ]);
})(window.SAGE = window.SAGE || {});
